kind: LocalConfig
apiversion: odo.openshift.io/v1alpha1
ComponentSettings:
  Type: java:8
  SourceLocation: ./
  SourceType: local
  Ports:
  - 8080/TCP
  - 8443/TCP
  - 8778/TCP
  Application: app
  Project: odo-project
  Name: java-hello-spring-dswk
  Url:
  - Name: java-hello-spring-dswk-8080
    Port: 8080
